name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions: # Add detailed permissions
  contents: write
  packages: write
  issues: write
  pull-requests: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.5'

      - name: Build
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o kanastar

      - name: Make execuable and archive binaries
        run: |
          chmod +x kanastar && tar -czvf kanastar-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz kanastar

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: kanastar-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
