name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions: # Add detailed permissions
  contents: read
  packages: read
  issues: write
  pull-requests: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version: '1.23.5'

      - name: Build
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o kanactl

      - name: Make execuable and archive binaries
        run: |
          chmod +x kanactl && tar -czvf kanactl-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz kanactl

      - name: Upload Release Assets
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
        with:
          files: kanactl-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
