name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.5'

      - name: Build
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o kanastar-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Archive binaries
        run: |
          tar -czvf kanastar-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz kanastar-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: kanastar-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}